@startuml
title: "Preparing Bills"
Server->OORMS: Selects 'Create Bills'
OORMS->Server: Changes buttons

loop While any orders are unnacounted for
    Server->OORMS: Selects seats on Order
    OORMS->Server: updates seat color \nto indicate seat is on bill
    Server->OORMS: Server Selects 'Add bill'
    OORMS->OORMS: adds bill to log
end
Server->OORMS: Presses done
OORMS->Server: Prints bill on printer tape






@enduml