@startuml
'https://plantuml.com/sequence-diagram



world ->GenghisKhan:do_turn
alt missing organs
    GenghisKhan->GenghisKhan:create_organs()

else
    GenghisKhan->GenghisKhan:reproduce_if_able()
    GenghisKhan->GenghisKhan: did_attack=maneuver_warfare()
    alt didn't attack
         GenghisKhan->Celia:move_in_direction(Direction.random())
    end alt
end alt


@enduml