@startuml
'https://plantuml.com/class-diagram

class GenghisKhan {
-instance_count:int
branch: lst[PhotoGland]
celia: Celia
type_censor: CreatureTypeSensor
womb: GenghisKhanPropagator

init()
-destroyed()
-instance_count()
do_turn()
create_organs()
reproduce_if_able()
maneuver_warfare()
}



@enduml